language: ruby
env: "CODECLIMATE_REPO_TOKEN=15ed3ea3aa5e152f478928dbb01e5747253e54be2b90553170931dbc842428c7"
rvm: 2.2.3
script:
  - bundle exec rspec spec/
before_script:
  - cp config/inventory_api_keys.travis.yml config/inventory_api_keys.yml
  - cp config/database.travis.yml config/database.yml
  - cp -f config/environments/development.travis.yml config/environments/development.yml
  - cp -f config/environments/test.travis.yml config/environments/test.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
addons:
  mariadb: '10.0'
